// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {domain} from '../models';

export function CreateBill(arg1:service.CreateBillInput):Promise<domain.Invoice>;

export function GetInvoice(arg1:number):Promise<domain.Invoice>;

export function ListInvoices(arg1:domain.InvoiceFilter):Promise<Array<domain.Invoice>>;
