// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBill(arg1) {
  return window['go']['app']['BillingHandler']['CreateBill'](arg1);
}

export function GetInvoice(arg1) {
  return window['go']['app']['BillingHandler']['GetInvoice'](arg1);
}

export function ListInvoices(arg1) {
  return window['go']['app']['BillingHandler']['ListInvoices'](arg1);
}
