// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['app']['CustomerHandler']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['app']['CustomerHandler']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['app']['CustomerHandler']['Get'](arg1);
}

export function List(arg1) {
  return window['go']['app']['CustomerHandler']['List'](arg1);
}

export function PurchaseHistory(arg1) {
  return window['go']['app']['CustomerHandler']['PurchaseHistory'](arg1);
}

export function Update(arg1) {
  return window['go']['app']['CustomerHandler']['Update'](arg1);
}
