// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Create(arg1:domain.Customer):Promise<domain.Customer>;

export function Delete(arg1:number):Promise<void>;

export function Get(arg1:number):Promise<domain.Customer>;

export function List(arg1:string):Promise<Array<domain.Customer>>;

export function PurchaseHistory(arg1:number):Promise<Array<domain.Invoice>>;

export function Update(arg1:domain.Customer):Promise<domain.Customer>;
