// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadDemoData() {
  return window['go']['app']['DemoHandler']['LoadDemoData']();
}
