// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PreviewReceipt(arg1) {
  return window['go']['app']['PrintHandler']['PreviewReceipt'](arg1);
}

export function PrintReceipt(arg1) {
  return window['go']['app']['PrintHandler']['PrintReceipt'](arg1);
}
