// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PreviewReceipt(arg1:number):Promise<string>;

export function PrintReceipt(arg1:number):Promise<void>;
