// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Categories():Promise<Array<string>>;

export function Create(arg1:domain.Product):Promise<domain.Product>;

export function Delete(arg1:number):Promise<void>;

export function Get(arg1:number):Promise<domain.Product>;

export function List(arg1:domain.ProductFilter):Promise<Array<domain.Product>>;

export function StockHistory(arg1:number):Promise<Array<domain.StockMovement>>;

export function Update(arg1:domain.Product):Promise<domain.Product>;
