// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Categories() {
  return window['go']['app']['ProductHandler']['Categories']();
}

export function Create(arg1) {
  return window['go']['app']['ProductHandler']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['app']['ProductHandler']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['app']['ProductHandler']['Get'](arg1);
}

export function List(arg1) {
  return window['go']['app']['ProductHandler']['List'](arg1);
}

export function StockHistory(arg1) {
  return window['go']['app']['ProductHandler']['StockHistory'](arg1);
}

export function Update(arg1) {
  return window['go']['app']['ProductHandler']['Update'](arg1);
}
