// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {domain} from '../models';

export function Create(arg1:service.CreatePurchaseInput):Promise<domain.Purchase>;

export function Get(arg1:number):Promise<domain.Purchase>;

export function List(arg1:domain.PurchaseFilter):Promise<Array<domain.Purchase>>;
