// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['app']['PurchaseHandler']['Create'](arg1);
}

export function Get(arg1) {
  return window['go']['app']['PurchaseHandler']['Get'](arg1);
}

export function List(arg1) {
  return window['go']['app']['PurchaseHandler']['List'](arg1);
}
