// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportSalesCSV(arg1, arg2) {
  return window['go']['app']['ReportsHandler']['ExportSalesCSV'](arg1, arg2);
}

export function LowStock() {
  return window['go']['app']['ReportsHandler']['LowStock']();
}

export function Profit(arg1, arg2) {
  return window['go']['app']['ReportsHandler']['Profit'](arg1, arg2);
}

export function Sales(arg1, arg2) {
  return window['go']['app']['ReportsHandler']['Sales'](arg1, arg2);
}

export function TopProducts(arg1, arg2, arg3) {
  return window['go']['app']['ReportsHandler']['TopProducts'](arg1, arg2, arg3);
}
