// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ExportSalesCSV(arg1:string,arg2:string):Promise<string>;

export function LowStock():Promise<Array<domain.Product>>;

export function Profit(arg1:string,arg2:string):Promise<domain.ProfitReport>;

export function Sales(arg1:string,arg2:string):Promise<domain.SalesSummary>;

export function TopProducts(arg1:string,arg2:string,arg3:number):Promise<Array<domain.TopProduct>>;
