// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSetting(arg1) {
  return window['go']['app']['SettingsHandler']['GetSetting'](arg1);
}

export function GetShopProfile() {
  return window['go']['app']['SettingsHandler']['GetShopProfile']();
}

export function SaveShopProfile(arg1) {
  return window['go']['app']['SettingsHandler']['SaveShopProfile'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['app']['SettingsHandler']['SetSetting'](arg1, arg2);
}
