// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetSetting(arg1:string):Promise<string>;

export function GetShopProfile():Promise<domain.ShopProfile>;

export function SaveShopProfile(arg1:domain.ShopProfile):Promise<domain.ShopProfile>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;
