// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['app']['SupplierHandler']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['app']['SupplierHandler']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['app']['SupplierHandler']['Get'](arg1);
}

export function List(arg1) {
  return window['go']['app']['SupplierHandler']['List'](arg1);
}

export function Update(arg1) {
  return window['go']['app']['SupplierHandler']['Update'](arg1);
}
